/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_glavo_llvm_internal_ir_ArrayTypeImpl */

#ifndef _Included_org_glavo_llvm_internal_ir_ArrayTypeImpl
#define _Included_org_glavo_llvm_internal_ir_ArrayTypeImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_glavo_llvm_internal_ir_ArrayTypeImpl
 * Method:    get
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_glavo_llvm_internal_ir_ArrayTypeImpl_get
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_glavo_llvm_internal_ir_ArrayTypeImpl
 * Method:    isValidElementType
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_glavo_llvm_internal_ir_ArrayTypeImpl_isValidElementType
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
