/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_glavo_llvm_internal_ir_SequentialTypeImpl */

#ifndef _Included_org_glavo_llvm_internal_ir_SequentialTypeImpl
#define _Included_org_glavo_llvm_internal_ir_SequentialTypeImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_glavo_llvm_internal_ir_SequentialTypeImpl
 * Method:    getNumElements
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_glavo_llvm_internal_ir_SequentialTypeImpl_getNumElements
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_glavo_llvm_internal_ir_SequentialTypeImpl
 * Method:    getElementType
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_glavo_llvm_internal_ir_SequentialTypeImpl_getElementType
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
