/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_glavo_llvm_internal_ir_ContextImpl */

#ifndef _Included_org_glavo_llvm_internal_ir_ContextImpl
#define _Included_org_glavo_llvm_internal_ir_ContextImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_glavo_llvm_internal_ir_ContextImpl
 * Method:    newInstance
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_glavo_llvm_internal_ir_ContextImpl_newInstance
  (JNIEnv *, jclass);

/*
 * Class:     org_glavo_llvm_internal_ir_ContextImpl
 * Method:    delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_glavo_llvm_internal_ir_ContextImpl_delete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_glavo_llvm_internal_ir_ContextImpl
 * Method:    getGlobal
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_glavo_llvm_internal_ir_ContextImpl_getGlobal
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
