/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_glavo_llvm_internal_ir_FunctionTypeImpl */

#ifndef _Included_org_glavo_llvm_internal_ir_FunctionTypeImpl
#define _Included_org_glavo_llvm_internal_ir_FunctionTypeImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_glavo_llvm_internal_ir_FunctionTypeImpl
 * Method:    get
 * Signature: (J[JZ)J
 */
JNIEXPORT jlong JNICALL Java_org_glavo_llvm_internal_ir_FunctionTypeImpl_get
  (JNIEnv *, jclass, jlong, jlongArray, jboolean);

/*
 * Class:     org_glavo_llvm_internal_ir_FunctionTypeImpl
 * Method:    isValidReturnType
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_glavo_llvm_internal_ir_FunctionTypeImpl_isValidReturnType
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_glavo_llvm_internal_ir_FunctionTypeImpl
 * Method:    isValidArgumentType
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_glavo_llvm_internal_ir_FunctionTypeImpl_isValidArgumentType
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_glavo_llvm_internal_ir_FunctionTypeImpl
 * Method:    isVarArg
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_glavo_llvm_internal_ir_FunctionTypeImpl_isVarArg
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_glavo_llvm_internal_ir_FunctionTypeImpl
 * Method:    getReturnType
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_glavo_llvm_internal_ir_FunctionTypeImpl_getReturnType
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_glavo_llvm_internal_ir_FunctionTypeImpl
 * Method:    getParamTypes
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_org_glavo_llvm_internal_ir_FunctionTypeImpl_getParamTypes
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
