/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_glavo_llvm_internal_ir_PointerTypeImpl */

#ifndef _Included_org_glavo_llvm_internal_ir_PointerTypeImpl
#define _Included_org_glavo_llvm_internal_ir_PointerTypeImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_glavo_llvm_internal_ir_PointerTypeImpl
 * Method:    get
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_org_glavo_llvm_internal_ir_PointerTypeImpl_get
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_glavo_llvm_internal_ir_PointerTypeImpl
 * Method:    isValidElementType
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_glavo_llvm_internal_ir_PointerTypeImpl_isValidElementType
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_glavo_llvm_internal_ir_PointerTypeImpl
 * Method:    isLoadableOrStorableType
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_glavo_llvm_internal_ir_PointerTypeImpl_isLoadableOrStorableType
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_glavo_llvm_internal_ir_PointerTypeImpl
 * Method:    getElementType
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_glavo_llvm_internal_ir_PointerTypeImpl_getElementType
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_glavo_llvm_internal_ir_PointerTypeImpl
 * Method:    getAddressSpace
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_glavo_llvm_internal_ir_PointerTypeImpl_getAddressSpace
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
