/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_glavo_llvm_internal_ir_TypeImpl */

#ifndef _Included_org_glavo_llvm_internal_ir_TypeImpl
#define _Included_org_glavo_llvm_internal_ir_TypeImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_glavo_llvm_internal_ir_TypeImpl
 * Method:    getVoidTy
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_glavo_llvm_internal_ir_TypeImpl_getVoidTy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_glavo_llvm_internal_ir_TypeImpl
 * Method:    getLabel
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_glavo_llvm_internal_ir_TypeImpl_getLabel
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_glavo_llvm_internal_ir_TypeImpl
 * Method:    getHalfTy
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_glavo_llvm_internal_ir_TypeImpl_getHalfTy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_glavo_llvm_internal_ir_TypeImpl
 * Method:    getFloatTy
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_glavo_llvm_internal_ir_TypeImpl_getFloatTy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_glavo_llvm_internal_ir_TypeImpl
 * Method:    getDoubleTy
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_glavo_llvm_internal_ir_TypeImpl_getDoubleTy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_glavo_llvm_internal_ir_TypeImpl
 * Method:    getMetadataTy
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_glavo_llvm_internal_ir_TypeImpl_getMetadataTy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_glavo_llvm_internal_ir_TypeImpl
 * Method:    getX86_FP80Ty
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_glavo_llvm_internal_ir_TypeImpl_getX86_1FP80Ty
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_glavo_llvm_internal_ir_TypeImpl
 * Method:    getFP128Ty
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_glavo_llvm_internal_ir_TypeImpl_getFP128Ty
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_glavo_llvm_internal_ir_TypeImpl
 * Method:    getPPC_FP128Ty
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_glavo_llvm_internal_ir_TypeImpl_getPPC_1FP128Ty
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_glavo_llvm_internal_ir_TypeImpl
 * Method:    getX86_MMXTy
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_glavo_llvm_internal_ir_TypeImpl_getX86_1MMXTy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_glavo_llvm_internal_ir_TypeImpl
 * Method:    getTokenTy
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_glavo_llvm_internal_ir_TypeImpl_getTokenTy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_glavo_llvm_internal_ir_TypeImpl
 * Method:    toString
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_glavo_llvm_internal_ir_TypeImpl_toString
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_glavo_llvm_internal_ir_TypeImpl
 * Method:    getContext
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_glavo_llvm_internal_ir_TypeImpl_getContext
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_glavo_llvm_internal_ir_TypeImpl
 * Method:    getTypeId
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_glavo_llvm_internal_ir_TypeImpl_getTypeId
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_glavo_llvm_internal_ir_TypeImpl
 * Method:    isFPOrFPVectorTy
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_glavo_llvm_internal_ir_TypeImpl_isFPOrFPVectorTy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_glavo_llvm_internal_ir_TypeImpl
 * Method:    isIntegerTy
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_glavo_llvm_internal_ir_TypeImpl_isIntegerTy
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_glavo_llvm_internal_ir_TypeImpl
 * Method:    isIntOrIntVectorTy
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_glavo_llvm_internal_ir_TypeImpl_isIntOrIntVectorTy__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_glavo_llvm_internal_ir_TypeImpl
 * Method:    isIntOrIntVectorTy
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_glavo_llvm_internal_ir_TypeImpl_isIntOrIntVectorTy__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_glavo_llvm_internal_ir_TypeImpl
 * Method:    isPtrOrPtrVectorTy
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_glavo_llvm_internal_ir_TypeImpl_isPtrOrPtrVectorTy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_glavo_llvm_internal_ir_TypeImpl
 * Method:    canLosslesslyBitCastTo
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_glavo_llvm_internal_ir_TypeImpl_canLosslesslyBitCastTo
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_glavo_llvm_internal_ir_TypeImpl
 * Method:    isEmptyTy
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_glavo_llvm_internal_ir_TypeImpl_isEmptyTy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_glavo_llvm_internal_ir_TypeImpl
 * Method:    getPrimitiveSizeInBits
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_glavo_llvm_internal_ir_TypeImpl_getPrimitiveSizeInBits
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_glavo_llvm_internal_ir_TypeImpl
 * Method:    getScalarSizeInBits
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_glavo_llvm_internal_ir_TypeImpl_getScalarSizeInBits
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_glavo_llvm_internal_ir_TypeImpl
 * Method:    getFPMantissaWidth
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_glavo_llvm_internal_ir_TypeImpl_getFPMantissaWidth
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
