/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_glavo_llvm_internal_ir_CompositeTypeImpl */

#ifndef _Included_org_glavo_llvm_internal_ir_CompositeTypeImpl
#define _Included_org_glavo_llvm_internal_ir_CompositeTypeImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_glavo_llvm_internal_ir_CompositeTypeImpl
 * Method:    getTypeAtIndex
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_org_glavo_llvm_internal_ir_CompositeTypeImpl_getTypeAtIndex
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_glavo_llvm_internal_ir_CompositeTypeImpl
 * Method:    indexValid
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_glavo_llvm_internal_ir_CompositeTypeImpl_indexValid
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
