/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_glavo_llvm_internal_ir_VectorTypeImpl */

#ifndef _Included_org_glavo_llvm_internal_ir_VectorTypeImpl
#define _Included_org_glavo_llvm_internal_ir_VectorTypeImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_glavo_llvm_internal_ir_VectorTypeImpl
 * Method:    get
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_org_glavo_llvm_internal_ir_VectorTypeImpl_get
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_glavo_llvm_internal_ir_VectorTypeImpl
 * Method:    isValidElementType
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_glavo_llvm_internal_ir_VectorTypeImpl_isValidElementType
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_glavo_llvm_internal_ir_VectorTypeImpl
 * Method:    getBitWidth
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_glavo_llvm_internal_ir_VectorTypeImpl_getBitWidth
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
